import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Naano: B2B LinkedIn Creator Marketplace",
  description: "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${plusJakarta.variable}`}>
      <body className="antialiased min-h-screen bg-canvas text-charcoal selection:bg-[#0A66C2]/15 selection:text-[#0A66C2]">
        {children}
      </body>
    </html>
  );
}
