"use client";

import React from "react";
import { ArrowRight, ShieldCheck, CheckCircle2, TrendingUp, Users } from "lucide-react";

interface HeroProps {
  onExploreClick: () => void;
}

export const Hero: React.FC<HeroProps> = ({ onExploreClick }) => {
  return (
    <section className="relative pt-32 pb-16 md:pt-40 md:pb-24 overflow-hidden flex flex-col items-center text-center px-4">
      {/* Background radial glow */}
      <div className="absolute top-12 left-1/2 -translate-x-1/2 w-[700px] h-[350px] bg-gradient-to-b from-[#EAE8E3]/60 to-transparent blur-3xl pointer-events-none -z-10 rounded-full" />

      {/* Trust Pill / Top Badge */}
      <div className="inline-flex items-center gap-2.5 bg-white border border-border rounded-full px-3.5 py-1.5 shadow-subtle mb-8">
        <div className="flex items-center -space-x-1">
          <span className="w-4 h-4 rounded-sm bg-accent-linkedin text-white flex items-center justify-center font-bold text-[10px]">
            in
          </span>
        </div>
        <span className="text-xs sm:text-sm font-medium text-charcoal">
          Where B2B brands work with creators
        </span>
      </div>

      {/* Main Headline */}
      <h1 className="max-w-4xl text-4xl sm:text-6xl md:text-7xl font-bold tracking-tight text-charcoal leading-[1.08]">
        The B2B LinkedIn <br className="hidden sm:inline" />
        Creator Marketplace<span className="text-accent-linkedin">.</span>
      </h1>

      {/* Subtitle */}
      <p className="mt-6 max-w-2xl text-base sm:text-xl text-muted-foreground leading-relaxed">
        Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads, and pipeline generated by every post.
      </p>

      {/* CTA Buttons */}
      <div className="mt-9 flex flex-col sm:flex-row items-center gap-4">
        <button
          onClick={onExploreClick}
          className="w-full sm:w-auto flex items-center justify-center gap-2 bg-charcoal hover:bg-charcoal-hover text-white text-base font-semibold px-7 py-3.5 rounded-xl shadow-card transition-all group"
        >
          <span>Explore marketplace</span>
          <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
        </button>

        <a
          href="#how-it-works"
          className="w-full sm:w-auto flex items-center justify-center gap-2 text-charcoal hover:text-black text-base font-semibold px-6 py-3.5 rounded-xl transition-colors hover:bg-border-light/60"
        >
          <span>See how Naano works</span>
          <ArrowRight className="w-4 h-4" />
        </a>
      </div>

      {/* Quick Proof Metrics */}
      <div className="mt-14 flex flex-wrap items-center justify-center gap-6 sm:gap-10 text-xs sm:text-sm text-muted-foreground font-medium">
        <div className="flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-600" />
          <span>Fixed price per post</span>
        </div>
        <div className="flex items-center gap-2">
          <TrendingUp className="w-4 h-4 text-accent-linkedin" />
          <span>Full-funnel attribution pixel</span>
        </div>
        <div className="flex items-center gap-2">
          <ShieldCheck className="w-4 h-4 text-charcoal" />
          <span>Vetted B2B audiences only</span>
        </div>
      </div>
    </section>
  );
};
